### ISSUE TITLE
Busy wait

### ISSUE THREAD

**Issue by NaturalSelect** [ShirasawaSama/Cake-Sandbox#2]
https://github.com/ShirasawaSama/Cake-Sandbox/blob/a20e7ebbf4be6b5a7b86da4fad2549702e9e59da/main.cpp#L287

use WaitForSingleObject
Document： https://docs.microsoft.com/zh-cn/windows/win32/api/synchapi/nf-synchapi-waitforsingleobject

**Comment by NaturalSelect** [comment]
The GetExitCodeProcess function returns a valid error code defined by the application only after the thread terminates. Therefore, an application should not use STILL_ACTIVE (259) as an error code. If a thread returns STILL_ACTIVE (259) as an error code, applications that test for this value could interpret it to mean that the thread is still running and continue to test for the completion of the thread after the thread has terminated, which could put the application into an infinite loop.

**Comment by ShirasawaSama** [comment]
#4
