### ISSUE TITLE
why not use SID？ :)

### ISSUE THREAD

**Issue by NaturalSelect** [ShirasawaSama/Cake-Sandbox#3]
https://github.com/ShirasawaSama/Cake-Sandbox/blob/a20e7ebbf4be6b5a7b86da4fad2549702e9e59da/main.cpp#L43

https://docs.microsoft.com/zh-cn/windows/win32/api/winnt/ns-winnt-sid

**Comment by ShirasawaSama** [comment]
建议直接发pr

**Comment by NaturalSelect** [comment]
啊这
